### ISSUE TITLE
RFID keypad not supported

### ISSUE THREAD

**Issue by rickardp** [aartse/athom.zipato#12]
I don’t know if it is within the scope of this app to support every Zipato device, but considering other z-wave home security devices are supported I think this is the right app for it.

Product link: https://www.zipato.com/product/mini-keypad-rfid

**Comment by idarlund** [comment]
I really support this one! Please add support for it.
I don't find any technical manuals on zipato.com, but theres a manual for the device to be downloaded here; https://www.tronika.no/en/index.php?controller=attachment&id_attachment=121

**Comment by aartse** [comment]
@rickardp has this device and is working on it :)

**Comment by rickardp** [comment]
@idarlund I have just migrated it to the new meshdriver to be compatible with SDK 2. If you are eager to try it, it could use some more testing.
Install manually from here: https://github.com/rickardp/athom.zipato
Just be aware that you will use the pre-release version for all Zipato devices.

**Comment by idarlund** [comment]
you can manually install apps like this with CLI @meyland, and there's a guide on how to do it over at the athom forum; https://forum.athom.com/discussion/1448/how-to-cli-install-method

**Comment by idarlund** [comment]
When trying to run this project, I get the following error:
C:\node-v8.9.4-win-x64>athom app run -p athom.zipato-rfid-keypad
┌────────────────────────────────────────────┐
│ Hey developer, we're hiring! View our open │
│ positions at https://go.athom.com/jobs     │
└────────────────────────────────────────────┘
✓ Validating app...
✘ Homey App did not validate against level `debug`:
schema is invalid: data.definitions['zwaveDevice'].properties['associationGroupsOptions'].properties['type'] should be object,boolean
Not installing, please fix the validation issues first

**Comment by aartse** [comment]
yesterday merged this branch into beta branch (and did some changes for homeyConfig). App (version 2.1.0) is now in review by athom.

i don't have the RFID device for testing, but the whole zipato app did run on my homey.
os: ubuntu
athom-cli version:  2.1.22
homey version: 1.5.11
node version: 8.11.1

can you check your athom-cli version? i think this tool checks the json scheme

**Comment by rickardp** [comment]
Works in 2.1.21

npm ls -g athom-cli
/usr/local/lib
`-- athom-cli@2.1.21

so maybe downgrading to 2.1.21 would work as a temporary solution?

**Comment by idarlund** [comment]
let me know if you want me to test it again. i do have the device.

**Comment by aartse** [comment]
i made changes to the beta branch to make it pass the validation. thnx @rickardp for the "signed" tip!
i submitted the new version to the beta channel in the store. Now waiting for approval by athom.

**Comment by idarlund** [comment]
roger that, waiting for it to be approved then :)

**Comment by idarlund** [comment]
I see that Zipato v2.1.0 is released today. I guess that includes the keypad beta?

**Comment by erlandjack** [comment]
To remove users and clear the event log in the desktop app doesn't work for me either, but it works in the android Homey preview app.

**Comment by rickardp** [comment]
@idarlund That works for me, but are you by any chance running Windows? I never tested the Homey app on Windows, and it may be using a different browser engine than the Mac version under the hood. If so, does it work in e.g. chrome?

**Comment by aartse** [comment]
someone has sent me the RFID keypad for debugging, so i can check these issues.

**Comment by erlandjack** [comment]
Maybe there is a difference between OS. I'm running Windows 7 and tested both the Desktop app and Chrome, Firefox and Opera browsers without success. However, there is no problem with my android smartphone.

**Comment by rickardp** [comment]
@erlandjack @aartse Sorry, I should have tried again before answering. This does not work for me either anymore. I believe Homey are now sandboxing the settings page in an iframe. The inspector says "Use of window.confirm is not allowed in a sandboxed frame when the allow-modals flag is not set."

The code will have to be refactored to use some kind of DOM-based dialog system instead of the standard confirm dialog then. Or if we could convince Athom to add "allow-modals".

This definitely worked before, so this must be a change in some recent firmware upgrade.

**Comment by joakim93** [comment]
I have this working quite allright I have 10 tags and they all work fine witho home and away buttons. Is it possible to configure so only pressing home button without tag sends userid 0 or something like that? Then i could make a flow that when my alarm is disarmed the door opens just by pressing home. The tags do open the door and disarm my alarm.

**Comment by aartse** [comment]
@rickardp, I have found some time to look into this, and an update is coming to fix some bugs.
@joakim93, unfortunately the RFID does not send a signal to homey if no tag can be read.

**Comment by jtyrvain** [comment]
I cannot pairing Mini RFID keypad. It's start pairing, but after "Retrieving command class versions ..." pairing ends with message "Could not reach the device anymore." I have try 10cm from Homey and 2m from Homey, but not help.

**Comment by pvdwijdeven** [comment]
Since lat week my keypad cannot communicate with Homey anymore. I tried unpair, now I cannot add device to z-wave network anymore (20 cm from Homey: added node, node found.. then error message "something went wrong". Is this something related to the zipato application (maybe bug in update?), or am I facing a more general z-wave issue?

**Comment by poblom** [comment]
@aartse Waiting eagerly for an update to the Mini RFID Keypad ;-)

**Comment by poblom** [comment]
Installed beta yesterday. The triggercards "System armed" and "System disarmed" don't seem to trigger (there are two of each by the way, with 3 or 4 tags attached respectively) my flows. Have I installed the wrong version or is there something missing??

**Comment by aartse** [comment]
is fixed in github, will be soon available on next beta update.

**Comment by jtyrvain** [comment]
Still not working. Still says "Could not reach the device anymore." when trying to pairing.

**Comment by aartse** [comment]
Ok, I will check this with my device.

**Comment by aartse** [comment]
i can remove and add the device without problem. i've checked the code, the pairing routine is handled by homey not in the app. 

Some things you could try:
- reset the device to factory settings
- change the batteries
- restart your homey
